### ISSUE TITLE
[DISCUSSION] Create a separate page for Clubs.

### ISSUE THREAD

**Issue by haxzie-xx** [so-sc/sosc-website#137]
We need a separate page to display all the details of clubs and campus ambassadors within SOSC.

**Comment by rumaan** [comment]
🌚

**Comment by afrzhussain** [comment]
@rumaan 🌚🌚

**Comment by haxzie-xx** [comment]
Implemented in #180 
We need things to discuss regarding further development.
Do we need a page within our website to describe the details of the clubs, or should we have the clubs design their own website? and link them to SOSC website? By this, it'll make the clubs more independent on what contents they need to put up on the website.

Open for discussions. :eyes: 

@coderhawk999 @rumaan @AbhiiGatty @jehadmohamedz @nathanielmathew @shravan1998 @Shanky1199 @swaaz @akshayrb22 @akashdeepb @navyabhat98 @monisha16

**Comment by navyabhat98** [comment]
I think this would be better idea it will help every club to get its own identity which is kind of lost right now.

**Comment by shravan1998** [comment]
In my opinion every club in sosc website is fine

**Comment by shravan1998** [comment]
Because that's why this collation is for

**Comment by AbhiiGatty** [comment]
Clubs usually have their own pages in own way. For example Django girls have their own page and it's not just look and colors which will be different but some clubs are provided with a website that they have to create to represent themselves. For now let's keep sosc website clean and restrict only to sosc content and redirect from clubs page to respective club main website because they deserve to have their own thing with their own identity and domain and look. @haxzie @navyabhat98 @shravan1998 @rumaan

**Comment by afrzhussain** [comment]
Agreeed

**Comment by haxzie-xx** [comment]
@AbhiiGatty yes indeed. We'll relay the message to all the club leads, especially DSC and Mozilla Sahyadri needs their own identity :+1: as you mentioned DjangoGirls has their own website but building a website for SOSWC will be a cool task the community can work on.
